# 0pdd configuration file.
# See for details: https://github.com/yegor256/0pdd
errors:
  - slava.semushin+0pdd@gmail.com
alerts:
  suppress:
    - on-scope
format:
  - short-title
  - title-length=120
